[package]
name = "foxglove-websocket-rs"
version = "0.1.0"
authors = ["Micah Chambers (eos) <mchambers@anduril.com>"]
edition = "2018"
publish = ["artifactory"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
